name: Deploy Resources (Demo)

concurrency:
  group: terraform-demo

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Action to perform (plan/apply/destroy)'
        options:
          - plan
          - apply
          - destroy
      resource:
        type: choice
        description: 'Resource'
        options:
          - 'common/storage/s3/example-bucket'
          - 'common/networking/azs'
          - 'common/networking/vpc'
          - 'common/networking/nlb'
          - 'common/security/groups/bastion-sg'
          - 'common/security/groups/ecs-services'
          - 'common/security/groups/gateway-sg'
          - 'common/networking/bastion'
          - 'common/networking/bastion-eip'
          - 'common/networking/api-gateway'
          - 'cluster/ecs-cluster'
          - 'cluster/service-discovery/cloud-map'
          - 'cluster/ecs-services/user-service'
          - 'common/security/cert'
          - 'common/networking/cloudfront/demo-app'
      region:
        type: choice
        description: 'AWS Region'
        options:
          - 'eu-west-1'
          - 'us-east-1'

env:
  # tf_version: 'v1.6.6'
  # tg_version: '0.54.7'
  #tf_version: 'v1.10.4'
  #tg_version: '0.71.2'
  #tg_container: 'tf-1.10.3-tg-0.71.1'
  environment: 'demo'
  base_dir: 'non-prod'
  aws_role: 'arn:aws:iam::966412459053:role/CCAwsInfraDemoGithubAction'
  #TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  #TF_LOG: 'DEBUG'

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    outputs:
      tg_dir: ${{ steps.set-dir.outputs.tg_dir }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Define Terragrunt Directory
        id: set-dir
        run: echo "tg_dir=${{ env.base_dir }}/${{ github.event.inputs.region }}/${{ env.environment }}/${{ github.event.inputs.resource }}" >> $GITHUB_OUTPUT
  
      - name: Annotate Pipeline
        run: echo "::notice ::Running Terragrunt ${{ github.event.inputs.action }} on Resource --> ${{ env.base_dir }}/${{ github.event.inputs.region }}/${{ env.environment }}/${{ github.event.inputs.resource }}"


  checks:
    name: Validate Terragrunt Configuration
    strategy:
      fail-fast: true
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/mm-camelcase/docker-terragrunt:tf-1.10.3-tg-0.71.1
    permissions:
      id-token: write
      contents: read
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Check HCL Formatting
        run: terragrunt hclfmt --terragrunt-check --terragrunt-diff -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }} --terragrunt-non-interactive 

      - name: Validate Configuration
        run: terragrunt validate -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }}

  plan:
    name: Generate Plan
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/mm-camelcase/docker-terragrunt:tf-1.10.3-tg-0.71.1
    permissions:
      id-token: write
      contents: read
    needs: [setup, checks]
    if: ${{ github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Run Terraform Plan
        run: |
          if [ "${{ github.event.inputs.action }}" = "plan" ] || [ "${{ github.event.inputs.action }}" = "apply" ]; then
            echo "Running terraform plan..."
            terragrunt run-all plan -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }}  --terragrunt-out-dir ${{ github.workspace }} --terragrunt-include-external-dependencies
          elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            echo "Running terraform plan -destroy..."
            terragrunt run-all plan -destroy -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }}  --terragrunt-out-dir ${{ github.workspace }} --terragrunt-include-external-dependencies
          fi

      - name: Run Terragrunt Show
        run: terragrunt show -json ${{ github.workspace }}/tfplan.tfplan  -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }} > plan-output.json

      - name: Visualise plan
        run: |
          tfplandoc generate -h | sed -n '/Key:/,/Usage:/p' | head -n -1 > plan.md
          tfplandoc generate plan-output.json -a >> plan.md

      - name: Find tfplan.tfplan and copy to root
        run: |
          #TFPLAN_PATH=$(find ${{ needs.setup.outputs.tg_dir }} -name "tfplan")
          #cp $TFPLAN_PATH ./tfplan
          cp ${{ github.workspace }}/tfplan.tfplan ./tfplan.tfplan


      # Upload the plan file and visual planas as artifacts
      - name: Upload Terraform Plan Output
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-output
          path: |
            ./plan.md
            ./tfplan.tfplan

      - name: summary
        run: |
          echo "_Resource:_ **${{ needs.setup.outputs.tg_dir }}**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat plan.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** Check logs for detailed plan" >> $GITHUB_STEP_SUMMARY

  approval:
    needs: plan
    runs-on: ubuntu-24.04
    environment:
      name: demo
    if: ${{ github.event.inputs.action != 'plan' }}
    steps:
      - name: Await Manual Approval
        run: echo "Waiting for manual approval before applying changes."


  apply:
    name: Apply Changes
    runs-on: ubuntu-24.04
    container:
      image: devopsinfra/docker-terragrunt:tf-1.10.3-tg-0.71.1
    permissions:
      id-token: write
      contents: read
    needs: [approval, setup, plan]
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: ${{ github.event.inputs.region }}

      - uses: actions/download-artifact@v4
        with:
          name: terraform-plan-output
          path: ${{ github.workspace }}/tfplan.tfplan

      - name: Run Terrafrom Apply
        run: terragrunt run-all apply -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }}  --terragrunt-out-dir "$GITHUB_WORKSPACE/tfplan.tfplan"  --terragrunt-non-interactive 
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Annotate Apply
        run: |
          echo "::notice ::Applied Resource: ${{ needs.setup.outputs.tg_dir }}"

  destroy:
    name: Destroy Resources
    runs-on: ubuntu-24.04
    container:
      image: devopsinfra/docker-terragrunt:tf-1.10.3-tg-0.71.1
    permissions:
      id-token: write
      contents: read
    needs: [approval, setup, plan]
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: ${{ github.event.inputs.region }}

      - uses: actions/download-artifact@v4
        with:
          name: terraform-plan-output
          path: ${{ github.workspace }}/tfplan.tfplan

      - name: Run Terrafrom Destroy
        #run: terragrunt run-all destroy -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }}  --terragrunt-out-dir "$GITHUB_WORKSPACE/tfplan.tfplan"  --terragrunt-non-interactive
        run: terragrunt run-all apply -terragrunt-working-dir ${{ needs.setup.outputs.tg_dir }}  --terragrunt-out-dir "$GITHUB_WORKSPACE/tfplan.tfplan"  --terragrunt-non-interactive
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Annotate Destroy
        run: |
          echo "::notice ::Destroyed Resource: ${{ needs.setup.outputs.tg_dir }}"
